-- I. CREATE TABLE
-- 1. Bang USER
CREATE TABLE APP_USER (
    USER_ID        NVARCHAR2(20)   PRIMARY KEY,
    USERNAME       NVARCHAR2(50)   NOT NULL UNIQUE,
    PASSWORD       NVARCHAR2(100)  NOT NULL,
    ROLE           NVARCHAR2(20)   NOT NULL DEFAULT 'CHUTAU'
);

-- 2. Bang ADMIN
CREATE TABLE ADMIN (
    MaAdmin        NVARCHAR2(20)    PRIMARY KEY,
    HoTen          NVARCHAR2(100)   NOT NULL,
    CoQuan         NVARCHAR2(100)   NOT NULL,
    CCCD           NVARCHAR2(20)    NOT NULL UNIQUE
);


-- 3. Bang CHU_TAU
CREATE TABLE CHU_TAU (
    MaChuTau        NVARCHAR2(20)   PRIMARY KEY,
    HoTen           NVARCHAR2(50)   NOT NULL,
    SDT             NVARCHAR2(20)   NOT NULL,
    DiaChi          NVARCHAR2(100)  NOT NULL,
    CCCD            NVARCHAR2(20)   NOT NULL UNIQUE,
    TrangThaiDuyet  NVARCHAR2(50)   NOT NULL DEFAULT 'DANG CHO'
);

-- 4. Bang TAU_CA
CREATE TABLE TAU_CA (
    MaTauCa            NVARCHAR2(20) PRIMARY KEY,
    SoDangKy           NVARCHAR2(50),
    LoaiTau            NVARCHAR2(50),
    ChieuDai           NUMBER(10,2),
    CongSuat           NUMBER(10,2),
    NamDongTau         INTEGER,
    TrangThaiDuyet     NVARCHAR2(20) DEFAULT 'DANG CHO',
    TrangThaiHoatDong  NVARCHAR2(20) DEFAULT 'DANG CHO|CHUA DK',
    MaChuTau           NVARCHAR2(20),
    MaNgheChinh        NVARCHAR2(20)
);

-- 5. Bang NGHE
CREATE TABLE NGHE (
    MaNghe        NVARCHAR2(20) PRIMARY KEY,
    TenNghe       NVARCHAR2(100) 
);

-- 6. BANG TAU_NGHE
CREATE TABLE TAU_NGHE (
    MaTauCa       NVARCHAR2(20)  NOT NULL,
    MaNghe        NVARCHAR2(20)  NOT NULL,
    VungHoatDong  NVARCHAR2(100),
    PRIMARY KEY (MaTauCa, MaNghe)
);

-- 7. Bang VI_PHAM
CREATE TABLE VI_PHAM (
    MaViPham            NVARCHAR2(20) PRIMARY KEY,
    ThoiGian            DATE         NOT NULL,
    ViTri               SDO_GEOMETRY NOT NULL,
    MoTa                NVARCHAR2(400),
    MaChuyenDanhBat     NVARCHAR2(20)
);

-- 8. Bang LOG_HAI_TRINH
CREATE TABLE LOG_HAI_TRINH (
    MaLogHaiTrinh       NVARCHAR2(20),
    MaChuyenDanhBat     NVARCHAR2(20),
    ThoiGian            DATE         NOT NULL,
    ViTri               SDO_GEOMETRY NOT NULL,
    VanToc              NUMBER(10,2),
    HuongDiChuyen       NVARCHAR2(100),
    PRIMARY KEY (MaLogHaiTrinh, MaChuyenDanhBat)
);

-- 9. Bang CHUYEN_DANH_BAT
CREATE TABLE CHUYEN_DANH_BAT (
    MaChuyenDanhBat     NVARCHAR2(20) PRIMARY KEY,
    NgayXuatBen         DATE,
    NgayCapBen          DATE,
    CangDi              NVARCHAR2(100),
    CangVe              NVARCHAR2(100),
    TongKhoiLuong       NUMBER(12,2),
    TrangThaiDuyet      NVARCHAR2(20) DEFAULT 'DANGCHO',
    TrangThaiHoatDong   NVARCHAR2(20) DEFAULT 'DANGCHO',
    MaTauCa             NVARCHAR2(20),
    MaNguTruong         NVARCHAR2(20)
);

-- 10. Bang ME_CA
CREATE TABLE ME_CA (
    MaMeCa              NVARCHAR2(20),
    MaChuyenDanhBat     NVARCHAR2(20),
    KhoiLuongMeCa       NUMBER(12,2),
    ThoiGianThaLuoi     DATE,
    ThoiGianKeoLuoi     DATE,
    ViTriKeoLuoi        SDO_GEOMETRY NOT NULL,
    PRIMARY KEY (MaMeCa, MaChuyenDanhBat)
);

-- 11. BANG DANHBAT_THUYSAN
CREATE TABLE DANHBAT_THUYSAN (
    MaThuySan           NVARCHAR2(20),
    MaMeCa              NVARCHAR2(20),
    MaChuyenDanhBat     NUMBER(12,2),
    KhoiLuong           NUMBER NOT NULL,
    PRIMARY KEY (MeThuySan, MaMeCa, MaChuyenDanhBat)
);

-- 12. Bang THUY_SAN
CREATE TABLE THUY_SAN (
    MaThuySan           NVARCHAR2(20) PRIMARY KEY,
    TenLoaiThuySan      NVARCHAR2(100)
);

-- 13. Bang NGU_TRUONG
CREATE TABLE NGU_TRUONG (
    MaNguTruong         NVARCHAR2(20) PRIMARY KEY,
    TenNguTruong        NVARCHAR2(100),
    ViTri               SDO_GEOMETRY NOT NULL,
    SoLuongTauHienTai   INTEGER,
    SoLuongTauToiDa     INTEGER
);

-- 14. Bang THOI_TIET
CREATE TABLE THOI_TIET (
    MaDuBao         NVARCHAR2(20) PRIMARY KEY,
    ThoiGianDuBao   DATE,
    KhuVucAnhHuong  NVARCHAR2(100),
    ChiTietDuBao    NVARCHAR2(400)
);

-- 15. Bang BAO
CREATE TABLE BAO (
    MaBao   NVARCHAR2(20) PRIMARY KEY,
    TenBao  NVARCHAR2(100)
);

-- 16. Bang LOG_DUONG_DI_BAO
CREATE TABLE LOG_DUONG_DI_BAO (
    MaLogDuongDi    NVARCHAR2(20) PRIMARY KEY,
    MaBao           NVARCHAR2(20) NOT NULL,
    ThoiGian        DATE         NOT NULL,
    ViTri           SDO_GEOMETRY NULL,
    MucDo           NUMBER(20),
    PRIMARY KEY (MaLogDuongDi, MaBao)
);

-- II. CREATE SEQUENCE


-- III. CREATE CONSTRAINT
-- i. CHECK
ALTER TABLE APP_USER ADD CONSTRAINT CK_APP_USER_1 CHECK (ROLE IN ('ADMIN', 'CHUTAU'));

ALTER TABLE CHU_TAU ADD CONSTRAINT CK_CHU_TAU_1 CHECK (TrangThaiDuyet IN ('DANG CHO', 'DA DUYET', 'TU CHOI'));

ALTER TABLE TAU_CA ADD CONSTRAINT CK_TAU_CA_1 CHECK (TrangThaiDuyet IN ('DANG CHO', 'DA DUYET', 'TU CHOI'));
ALTER TABLE TAU_CA ADD CONSTRAINT CK_TAU_CA_2 CHECK (TrangThaiHoatDong IN ('DANG CHO|CHUA DK', 'DANG CHO|DA DK', 'DANG HOAT DONG'));

ALTER TABLE CHUYEN_DANH_BAT ADD CONSTRAINT CK_CHUYEN_DANH_BAT_1 CHECK (TrangThaiDuyet IN ('DANG CHO', 'DA DUYET', 'TU CHOI'));
ALTER TABLE CHUYEN_DANH_BAT ADD CONSTRAINT CK_CHUYEN_DANH_BAT_2 CHECK (TrangThaiHoatDong IN ('DANG CHO', 'DANG DAN BAT', 'HOAN THANH'));

-- ii. FOREIGN KEY
ALTER TABLE ADMIN ADD CONSTRAINT FK_ADMIN_1 FOREIGN KEY (MaAdmin) REFERENCES APP_USER(USER_ID);

ALTER TABLE CHU_TAU ADD CONSTRAINT FK_CHU_TAU_1 FOREIGN KEY (MaChuTau) REFERENCES APP_USER(USER_ID);

ALTER TABLE TAU_CA ADD CONSTRAINT FK_TAU_CA_1 FOREIGN KEY (MaChuTau) REFERENCES CHU_TAU(MaChuTau);
ALTER TABLE TAU_CA ADD CONSTRAINT FK_TAU_CA_2 FOREIGN KEY (MaNgheChinh) REFERENCES NGHE(MaNghe);

ALTER TABLE TAU_NGHE ADD CONSTRAINT FK_TAU_NGHE_1 FOREIGN KEY (MaTauCa) REFERENCES TAU_CA(MaTauCa);
ALTER TABLE TAU_NGHE ADD CONSTRAINT FK_TAU_NGHE_2 FOREIGN KEY (MaNghe) REFERENCES NGHE(MaNghe);

ALTER TABLE VI_PHAM ADD CONSTRAINT FK_VI_PHAM_1 FOREIGN KEY (MaChuyenDanhBat) REFERENCES CHUYEN_DANH_BAT(MaChuyenDanhBat);

ALTER TABLE LOG_HAI_TRINH ADD CONSTRAINT FK_LOG_HAI_TRINH_1 FOREIGN KEY (MaChuyenDanhBat) REFERENCES CHUYEN_DANH_BAT(MaChuyenDanhBat);

ALTER TABLE CHUYEN_DANH_BAT ADD CONSTRAINT FK_CHUYEN_DANH_BAT_1 FOREIGN KEY (MaTauCa) REFERENCES TAU_CA(MaTauCa);
ALTER TABLE CHUYEN_DANH_BAT ADD CONSTRAINT FK_CHUYEN_DANH_BAT_2 FOREIGN KEY (MaNguTruong) REFERENCES NGU_TRUONG(MaNguTruong);

ALTER TABLE ME_CA ADD CONSTRAINT FK_ME_CA_1 FOREIGN KEY (MaChuyenDanhBat) REFERENCES CHUYEN_DANH_BAT(MaChuyenDanhBat);

ALTER TABLE DANHBAT_THUYSAN ADD CONSTRAINT FK_DANHBAT_THUYSAN_1 FOREIGN KEY (MaThuySan) REFERENCES THUY_SAN(MaThuySan);
ALTER TABLE DANHBAT_THUYSAN ADD CONSTRAINT FK_DANHBAT_THUYSAN_2 FOREIGN KEY (MaMeCa) REFERENCES ME_CA(MaMeCa);
ALTER TABLE DANHBAT_THUYSAN ADD CONSTRAINT FK_DANHBAT_THUYSAN_3 FOREIGN KEY (MaChuyenDanhBat) REFERENCES CHUYEN_DANH_BAT(MaChuyenDanhBat);


-- IV. CREATE TRIGGER

-- V. CREATE PROCEDURE

-- VI. CREATE FUNCTION

-- VII. TEST CASE
